// Ambient declarations for CSS imports (src/global.css, *.module.css) —
// standard TypeScript-for-CSS-Modules pattern, not Expo-specific. Without
// this, typechecking depends on expo-env.d.ts/.expo/types being present,
// which are gitignored and only ever get generated by running the `expo
// start` dev server at least once — real on a dev machine, never true on a
// fresh clone or in CI. This makes the typecheck itself deterministic
// everywhere instead of depending on local machine state.
declare module '*.css';
declare module '*.module.css' {
  const classes: { [key: string]: string };
  export default classes;
}
