/**
 * Vervein addition, not in the vault — what each exercise actually needs,
 * item by item, so the engine can plan around the equipment someone owns
 * rather than the library's own three-tier `equipment` field (none /
 * minimal / full_gym), which can't tell a dumbbell move from a barbell one.
 *
 * Data: data/exercise-equipment.json, generated by
 * scripts/tag-exercise-equipment.js (name rules plus hand-reviewed
 * overrides). Each entry lists alternatives, any one of which is enough;
 * each alternative is the set of items it needs together — a goblet squat
 * is [["dumbbell"], ["kettlebell"]], an incline dumbbell press is
 * [["bench", "dumbbell"]]. 'gym' marks anything only a full gym has
 * (cables, machines, sleds…), which no home list can satisfy.
 */
import requirementData from './data/exercise-equipment.json';
import type { Exercise } from './types';

const REQUIREMENTS: Record<string, string[][]> = requirementData;

/**
 * `owned` null means no item-level limit (a full gym, or a caller with no
 * equipment answer at all) — the tier ceiling alone decides, as before this
 * existed. An exercise the tagging script has never seen counts as needing a
 * gym unless the library itself calls it bodyweight: an untagged new entry
 * can then only ever be left out, never handed to someone without the kit.
 */
export function hasEquipmentFor(ex: Exercise, owned: readonly string[] | null | undefined): boolean {
  if (owned == null) return true;
  const alternatives = REQUIREMENTS[ex.id];
  if (!alternatives) return ex.equipment === 'none';
  if (alternatives.length === 0) return true;
  return alternatives.some((items) => items.every((item) => owned.includes(item)));
}

/** For tests and diagnostics — the raw alternatives, or undefined if untagged. */
export function equipmentRequirementsFor(exerciseId: string): string[][] | undefined {
  return REQUIREMENTS[exerciseId];
}
